# FROM kong/kong-gateway:3.14

# USER root

# RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-venv && rm -rf /var/lib/apt/lists/*

# RUN python3 -m venv /opt/kong-python
# RUN /opt/kong-python/bin/pip install --no-cache-dir kong-pdk httpx pyjwt

# COPY plugin.py /plugins/plugin.py

# USER kong

FROM kong/kong-gateway:3.14

USER root
COPY plugins/acuvity-guard /usr/local/share/lua/5.1/kong/plugins/acuvity-guard
USER kong